# Generated by Django 6.0.3 on 2026-04-06 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('recuperado', 'Recuperado')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
                ('movil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recuperado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
                ('movil_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('medicamento', 'fecha_vencimiento')},
            },
        ),
        migrations.CreateModel(
            name='StockMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movil')),
            ],
            options={
                'ordering': ['movil', 'medicamento', 'fecha_vencimiento'],
                'unique_together': {('movil', 'medicamento', 'fecha_vencimiento')},
            },
        ),
    ]
