# Generated by Django 6.0.3 on 2026-04-07 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vencido'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario en la moneda local', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sin_precio_definido', models.BooleanField(default=False)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
                ('movil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movil')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
