# Generated by Django 6.0.3 on 2026-04-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicamento_precio_unitario_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='exclude_from_expenses',
            field=models.BooleanField(default=False, help_text='Marcar para excluir del cálculo de gastos'),
        ),
    ]
