# Generated by Django 6.0.3 on 2026-04-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_compra_exclude_from_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='exclude_from_expenses',
        ),
        migrations.AddField(
            model_name='compra',
            name='contar_como_gasto',
            field=models.BooleanField(default=True, help_text='Marcar para incluir en cálculo de gastos'),
        ),
        migrations.AddField(
            model_name='compra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado al total', max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_sin_gasto',
            field=models.CharField(blank=True, help_text='Motivo si no se cuenta como gasto', max_length=255, null=True),
        ),
    ]
