# Generated by Django 6.0.3 on 2026-04-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_compra_exclude_from_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_mensual', models.DecimalField(decimal_places=2, default=10000, help_text='Límite máximo de gastos mensuales', max_digits=12)),
                ('porcentaje_alerta', models.IntegerField(default=80, help_text='Porcentaje del límite para mostrar alerta (0-100)')),
            ],
            options={
                'verbose_name': 'Configuración de Gastos',
                'verbose_name_plural': 'Configuración de Gastos',
            },
        ),
    ]
